name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HTML Validation
        run: echo "HTML OK"

      - name: CSS Validation
        run: echo "CSS OK"

      - name: JavaScript Validation
        run: echo "JS OK"
